[tool.poetry]
name = "cadastro-de-cliente-st"
version = "0.1.0"
description = ""
authors = ["Larissa Nathanna Gatto <larissangatto@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.57.0"
pandas = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
